name: pr
on:
    pull_request:
        types: [opened, synchronize]
jobs:
    pr:
        runs-on: ubuntu-22.04
        steps:
            - name: test
              run: "echo ${{github.head_ref}}"

